name: Checkout repository and display files
on: [push]
jobs:
  checkout-repository-and-display-files-manually:
    runs-on: ubuntu-latest
    steps:
      - name: list files before checkout
        run: ls -a
      - name: checkout repository
        run: |
          git init
          git remote add origin "https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY.git"
          git fetch origin
          git checkout main
      - name: list files after checkout
        run: ls -a
        