name: Repository events
on: [push, pull_request, issues]

jobs:
  test-repository-event-triggering:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo $GITHUB_SHA
          echo $GITHUB_REF
      - uses: actions/checkout@v4
      