name: Repository events
on:
  # push:
  pull_request: 
    types: [opened, closed, reopened, assigned]
  issues: 
    types: [opened, reopened]

jobs:
  # test-repository-event-triggering:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - run: |
  #         echo $GITHUB_SHA
  #         echo $GITHUB_REF
  # gh pr edit $PR_URL --add-label mylabel

  edit-pr-add-label:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
      PR_URL: ${{ github.event.pull_request.html_url }}

    permissions: 
      pull-requests: write
      
    steps:
      - run: |
          echo "Hello world"    
          echo $PR_URL
          gh pr edit $PR_URL --add-label mylabel
          
  edit-pr-add-comment:
    runs-on: ubuntu-latest
    needs: edit-pr-add-label
    
    env:
      GH_TOKEN: ${{ github.token }}
      PR_URL: ${{ github.event.pull_request.html_url }}

    permissions: 
      pull-requests: write
    
    steps:
      - run: gh pr comment $PR_URL --body "mylabel"
