name: Repository events
on:
  pull_request_target: 
    types: [opened, closed, reopened, assigned]

jobs:
  edit-pr-add-label:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
      PR_URL: ${{ github.event.pull_request.html_url }}

    permissions: 
      pull-requests: write
      id-token: write
      
    steps:
      - run: |
          echo "Hello world"    
          echo $PR_URL
          gh pr edit $PR_URL --add-label mylabel
          
  edit-pr-add-comment:
    runs-on: ubuntu-latest
    needs: edit-pr-add-label
    
    env:
      GH_TOKEN: ${{ github.token }}
      PR_URL: ${{ github.event.pull_request.html_url }}

    permissions: 
      pull-requests: write
    
    steps:
      - run: gh pr comment $PR_URL --body "mylabel"
