name: Repository events
on:
  push:
  pull_request: 
    types: [opened, closed, reopened, assigned]
  issues: 
    types: [opened, reopened]

jobs:
  test-repository-event-triggering:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo $GITHUB_SHA
          echo $GITHUB_REF
  another-job:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
      PR_URL: ${{ github.event.pull_request.html_url }}

    steps:
      - run: |
          echo "Hello world"
          gh pr edit $PR_URL --add-label mylabel        
