name: Simple JS action
on: [push]
jobs:
  simple-js-action:
    runs-on: ubuntu-latest
    steps:
      - name: display greeting
        id: display-greeting
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: Abdullah
      - name: show output of greeting
        run: echo "${{ steps.display-greeting.outputs.time }}"
