name: Working directory and shell
on: [push]
defaults:
  run:
    shell: bash
jobs:
  working-dirs-shell-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: display working directory and list files
        run: |
          pwd
          ls -a
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
      - name: change working directory
        working-directory: /home/runner
        run: pwd
  working-dirs-shell-windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: pwsh
    steps:
      - name: display working directory and list files
        run: |
          Get-Location
          dir
          echo $env:GITHUB_SHA
          echo $env:GITHUB_REPOSITORY
          echo $env:GITHUB_WORKSPACE
      - name: run python commands
        shell: python
        run: |
          import platform
          print(platform.processor())
